org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false

minecraft_version=1.10.2
minecraft_version_range=[1.10.2]
forge_version=12.18.3.2511
forge_version_range=[12.18.3.2511,)
loader_version_range=[12,)
mapping_channel=stable
mapping_version=29-1.10.2

loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
java_setup_version=8.0.502+7
gradle_java_version=17
curseforge_project_id=240985

mod_id=electricadvantage
mod_name=Electric Advantage
mod_license=GPL-3.0-only
mod_version=2.2.1.110021
mod_group=com.mcmoddev.electricadvantage
mod_authors=DrCyano
mod_description=Electrical generation, storage, and machines for the Power Advantage platform.

cf_requirements=power-advantage,base-metals
cf_optionals=
cf_versions=1.10.2

poweradvantage_version=2.4.1.110021
poweradvantage_source_repository=MinecraftModDevelopmentMods/PowerAdvantage
poweradvantage_source_ref=6958ed2dfdd745ebc1f614a32072765af061fe8e
poweradvantage_deobf_sha256=2C2B688152C62A48A458ED15918D994BE0F9C371EA77C195D92D2EC5531E7CB5
